#line 2 "scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_acclist[513] =
    {   0,
       20,   20,   42,   42,   13,   13,   48,   48,   49,   49,
       44,   44,   58,   56,   57,    8,   34,   56,   57,   41,
       57,   40,   56,   57,   29,   40,   56,   57,   32,   40,
       56,   57,    7,   36,   40,   56,   57,   40,   56,   57,
        6,   38,   40,   56,   57,   40,   56,   57,    9,   33,
       40,   56,   57,    5,   27,   39,   40,   56,   57,   35,
       40,   56,   57,    9,   40,   56,   57,    9,   40,   56,
       57,    9,   40,   56,   57,    9,   40,   56,   57,    8,
       34,   56,   57,    1,   40,   56,   57,   40,   56,   57,
        9,   40,   56,   57,   24,   57,   20,   57,   26,   57,

       57,   24,   25,   57,   24,   25,   57,   24,   25,   57,
       25,   57,   24,   25,   57,   24,   25,   57,   20,   57,
        1,   24,   25,   57,   24,   25,   57,   24,   25,   57,
       34,   57,   40,   57,   29,   40,   57,   32,   40,   57,
       36,   40,   57,   40,   57,   38,   40,   57,   40,   57,
       10,   33,   40,   57,   27,   39,   40,   57,   35,   40,
       57,   10,   40,   57,   10,   40,   57,   10,   40,   57,
       10,   40,   57,   34,   57,    1,   40,   57,   40,   57,
       10,   40,   57,   15,   33,   40,   57,   15,   40,   57,
       15,   40,   57,   15,   40,   57,   15,   40,   57,   15,

       40,   57,   42,   57,   43,   57,   42,   57,   42,   57,
       42,   57,    1,   42,   57,   42,   57,   42,   57,   13,
       57,   12,   57,   12,   57,   12,   57,   13,   57,    1,
       57,   57,   12,   57,   14,   33,   40,   57,   14,   40,
       57,   14,   40,   57,   14,   40,   57,   14,   40,   57,
       14,   40,   57,   19,   57,   18,   57,   18,   57,    9,
       18,   57,   16,   18,   57,    9,   18,   57,    9,   18,
       57,   19,   57,    1,   18,   57,   18,   57,    9,   18,
       57,   11,   33,   40,   57,   11,   40,   57,   11,   40,
       57,   11,   40,   57,   11,   40,   57,   11,   40,   57,

       48,   57,   48,   55,   57,   54,   57,   54,   57,   52,
       54,   57,   53,   54,   57,   52,   54,   57,   52,   54,
       57,   48,   57,    1,   54,   57,   54,   57,   52,   54,
       57,   49,   57,   49,   55,   57,   54,   57,   49,   57,
       44,   57,   47,   57,   46,   57,   44,   57,   44,   57,
       44,   57,    1,   44,   57,   44,   57,   44,   57,    8,
       34,   37,   33,   28,    9,   33,    9,   35,    9,   31,
       30,    9,    1,    3,   37,    4,   24,   20,   24,   24,
       21,   24,   24,    1,   24,   24,   34,   10,   33,   10,
       10,   10,   15,   33,   15,   15,   15,   42,   42,   42,

       42,    1,   42,   42,    4,   42,   13,   12,   12,   12,
       14,   33,   14,   14,   14,   19,   17,   11,   33,   11,
       11,   11,   48,   52,   52,   52,   49,   50,   44,   45,
       44,   44,   44,    1,   44,   44,    4,   44,   33,    9,
        9,    4,   22,   24,   22,   23,   24,   23,   24,   24,
       10,   10,   15,   15,   42,   42,    4,   42,   12,   12,
       14,   14,   17,   11,   11,   51,   52,   52,   44,   44,
        4,   44,    9,    9,   24,   24,   10,   10,   15,   15,
       42,   42,   12,   12,   14,   14,   11,   11,   52,   52,
       44,   44,    2,    9,    2,   24,    2,   10,    2,   15,

        2,   42,    2,   12,    2,   14,    2,   11,    2,   52,
        2,   44
    } ;

static yyconst short int yy_accept[295] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    3,    3,    4,
        5,    6,    7,    7,    7,    7,    7,    7,    7,    8,
        9,   10,   11,   12,   13,   14,   16,   20,   22,   25,
       29,   33,   38,   41,   46,   49,   54,   60,   64,   68,
       72,   76,   80,   84,   88,   91,   95,   97,   99,  101,
      102,  105,  108,  111,  113,  116,  119,  121,  125,  128,
      131,  133,  135,  138,  141,  144,  146,  149,  151,  155,
      159,  162,  165,  168,  171,  174,  176,  179,  181,  184,
      188,  191,  194,  197,  200,  203,  205,  207,  209,  211,
      213,  216,  218,  220,  222,  224,  226,  228,  230,  232,

      233,  235,  239,  242,  245,  248,  251,  254,  256,  258,
      260,  263,  266,  269,  272,  274,  277,  279,  282,  286,
      289,  292,  295,  298,  301,  303,  306,  308,  310,  313,
      316,  319,  322,  324,  327,  329,  332,  334,  337,  339,
      341,  343,  345,  347,  349,  351,  353,  356,  358,  360,
      362,  363,  364,  365,  365,  365,  367,  368,  369,  370,
      371,  372,  373,  373,  374,  374,  375,  376,  377,  378,
      379,  380,  380,  381,  381,  382,  383,  384,  386,  387,
      388,  388,  390,  391,  392,  393,  393,  395,  396,  397,
      398,  399,  400,  401,  402,  404,  405,  407,  408,  408,

      409,  410,  411,  411,  413,  414,  415,  416,  417,  418,
      418,  420,  421,  422,  423,  424,  424,  424,  425,  426,
      427,  428,  429,  430,  431,  431,  432,  433,  434,  436,
      437,  439,  440,  441,  442,  443,  445,  446,  448,  449,
      450,  451,  452,  453,  454,  455,  456,  457,  459,  460,
      461,  462,  463,  464,  465,  466,  467,  467,  468,  469,
      470,  471,  473,  474,  475,  476,  477,  478,  479,  480,
      481,  482,  483,  484,  485,  486,  487,  488,  489,  490,
      491,  492,  493,  495,  497,  499,  501,  503,  505,  507,
      509,  511,  513,  513

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    6,    6,   10,   11,
       12,   13,   14,   15,   16,   17,    6,   18,   19,   20,
       21,   18,   18,   18,   18,   18,   18,    6,   22,   23,
       23,   23,    6,    6,   25,   25,   26,   27,   28,   25,
       25,   29,   30,   31,   32,   25,   25,   25,   25,   33,
       25,   25,   34,   35,   25,   25,   25,   29,   25,   25,
        6,    6,    6,    6,   24,    6,   25,   25,   26,   27,

       28,   25,   25,   29,   30,   31,   32,   25,   25,   25,
       25,   33,   25,   25,   34,   35,   25,   25,   25,   29,
       25,   25,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[36] =
    {   0,
        1,    2,    3,    4,    4,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    5,    6,    5,    5,    5,
        5,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[317] =
    {   0,
        0,   34,   61,   95,  129,   43,  147,   47,   41,  181,
      215,   74,  233,  183,  268,  185,  286,  320,  347,  381,
       89,  407,   56,  433,  929,  930,   36,  930,  930,  930,
      930,  930,  915,   95,  466,  479,  930,  904,  500,  895,
       36,  893,  105,    0,   54,  919,    0,   48,  930,  930,
        0,  196,  319,   78,  892,  890,  115,  383,  388,  916,
      122,  930,  930,  930,  930,  907,  186,    0,  513,  930,
      896,  534,  887,   78,  885,  330,    0,  108,  911,  547,
      568,  884,  185,  882,  908,    0,  930,  881,  879,  897,
        0,  906,  903,  197,  321,  390,  138,  414,    0,  904,

      166,  581,  602,  875,  204,  873,  899,  336,  930,  377,
        0,  930,  872,  870,  424,    0,  898,  895,  615,  636,
      868,  332,  866,  892,  399,  428,  930,  424,  431,  930,
      442,  224,  476,    0,  893,  408,  460,  472,  420,  488,
        0,  930,  305,  864,  862,  880,  872,   55,  878,  452,
      930,  505,  555,    0,  573,    0,    0,  930,  849,  930,
      930,  846,  868,    0,  867,  930,  862,    0,    0,  447,
      621,  846,  654,  838,  658,  808,  800,  663,  670,  674,
        0,    0,    0,  790,  782,    0,    0,    0,  783,  776,
        0,  777,  772,  798,    0,  797,    0,  664,  758,  736,

      653,  296,    0,    0,    0,  738,  735,  681,  670,    0,
        0,    0,  736,  733,  690,  684,  731,  723,  669,  387,
      704,  696,    0,  930,  341,  724,  693,  499,  705,  533,
      653,  692,  636,  619,    0,    0,  930,    0,  930,  611,
      596,  601,  585,  578,  570,  569,  551,    0,  422,  439,
      544,  536,  696,  509,  494,  930,  706,  651,  528,  457,
      449,  442,  372,  700,  349,  709,  296,  712,  274,  715,
      222,  718,  709,  722,   90,  726,   84,  729,  720,  737,
       69,  740,    0,    0,    0,    0,    0,   55,    0,    0,
       46,    0,  930,  768,  774,  780,  786,  792,  798,  803,

      809,  815,  821,  827,  833,  839,   49,   32,  845,  850,
      856,  862,  868,  874,  880,  886
    } ;

static yyconst short int yy_def[317] =
    {   0,
      293,    1,  294,  294,  293,    5,    5,    7,  295,  295,
      293,   11,    7,   13,  293,   15,   13,   17,  293,   19,
       19,   19,  296,  296,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,   36,   39,
       39,   39,  293,  297,  298,   39,  299,  293,  293,  293,
      299,  300,  301,  293,  299,  299,  293,  302,  303,  299,
      293,  293,  293,  293,  293,  293,  293,   35,  293,  293,
      293,   69,   72,   72,   72,  293,  297,  298,   72,  293,
       80,   81,   81,   81,   81,  304,  293,  304,  304,  304,
      305,  306,  304,  293,  307,  307,   96,  293,  297,  298,

       96,  293,  102,  103,  103,  103,  103,  293,  293,  293,
       39,  293,   39,   39,  293,  297,  298,   39,  293,  119,
      120,  120,  120,  120,  293,  293,  293,  293,  308,  293,
      308,  131,  293,  297,  298,  131,  293,  293,  293,  293,
      309,  293,  293,  309,  309,  309,  310,  311,  309,  293,
      293,  293,  293,   39,  293,   36,   39,  293,   39,  293,
      293,   39,  298,  297,  298,  293,  298,  312,  299,  293,
      300,  313,  301,  314,  293,  299,  299,  302,  303,  293,
       72,   69,   72,   72,   72,   81,   80,   81,   81,   81,
      304,  304,  304,  306,  305,  306,  315,  293,   96,   96,

       96,   96,  103,  102,  103,  103,  103,  293,  293,  120,
      119,  120,  120,  120,  293,  293,  131,  131,  131,  131,
      293,  293,  309,  293,  293,  309,  309,  311,  310,  311,
      316,  293,   39,   39,  312,  299,  293,  299,  293,  299,
      299,   72,   72,   81,   81,  304,  304,  315,   96,   96,
      103,  103,  293,  120,  120,  293,  293,  131,  131,  309,
      309,  316,   39,   39,  299,  299,   72,   72,   81,   81,
      304,  304,   96,   96,  103,  103,  120,  120,  131,  131,
      309,  309,   39,  299,   72,   81,  304,   96,  103,  120,
      131,  309,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293
    } ;

static yyconst short int yy_nxt[966] =
    {   0,
       26,   27,   28,   27,   27,   29,   30,   29,   29,   31,
       32,   29,   33,   29,   34,   29,   35,   36,   36,   36,
       36,   37,   38,   29,   39,   39,   39,   40,   41,   39,
       39,   39,   39,   42,   39,   43,  218,  150,   43,  150,
      150,   44,  160,   87,   76,  161,   45,   76,   76,  170,
       77,   76,  170,  200,   77,   78,  166,  166,  142,   78,
       46,   47,   48,   49,   50,   48,  167,   52,   88,   79,
       53,  165,  143,   85,   89,   98,  218,   54,   98,  175,
      175,   99,  175,  144,  160,  200,  100,  161,   55,  145,
      137,  138,  137,  137,   56,   47,   57,   49,   50,   57,

      101,   52,   58,  292,   53,  139,  150,   59,  150,  150,
      166,   54,  152,  152,  152,  152,  170,  163,  290,  170,
      167,   60,   55,  180,  289,  180,  180,  163,   56,   50,
       61,   28,   61,   61,   62,   63,   62,   62,   64,   65,
       62,   66,   62,   67,   62,   68,   69,   69,   69,   69,
       70,   71,   62,   72,   72,   72,   73,   74,   72,   72,
       72,   72,   75,   72,   80,   80,   80,   80,  200,  202,
      168,   81,   81,   81,   82,   83,   81,   81,   81,   81,
       84,   81,   90,   87,   76,   90,  115,   76,   91,  115,
       77,  160,  116,   92,  161,   78,  200,  117,  198,  172,

      172,  198,  169,  152,  152,  152,  152,   93,   88,  107,
      160,  118,  172,  161,   89,   50,   94,   50,   50,   94,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   95,   95,   95,   95,   50,   50,   50,   95,
       95,   95,   96,   95,   95,   95,   95,   95,   97,   95,
      102,  102,  102,  102,  218,  220,  287,  103,  103,  103,
      104,  105,  103,  103,  103,  103,  106,  103,   50,  108,
       50,  108,  108,  109,  109,  109,  109,  109,  109,  109,
      109,  110,  109,  109,  109,  111,  111,  111,  111,  112,
      109,  109,  111,  111,  111,  113,  111,  111,  111,  111,

      111,  114,  111,  119,  119,  119,  119,  224,  286,  225,
      120,  120,  120,  121,  122,  120,  120,  120,  120,  123,
      120,   76,  174,  174,   76,  250,  200,   77,  169,  199,
      285,  180,   78,  180,  180,  174,  199,  208,  160,  208,
      208,  161,  163,  224,  199,  225,  124,   50,  125,  126,
      125,  125,  127,  127,  127,  127,  127,  128,  127,  127,
      127,  127,  127,  127,  129,  129,  129,  129,  130,  127,
      127,  129,  129,  129,  131,  129,  129,  129,  129,  129,
      132,  129,  133,  284,  164,  133,  164,  164,  134,  165,
      166,  165,  165,  135,  209,  209,  209,  209,  199,  164,

      215,  215,  215,  215,  165,  199,  283,  136,  140,  138,
      137,  140,  168,  199,  134,  198,  259,  218,  198,  135,
      201,  222,  222,  139,  222,  208,  163,  208,  208,  215,
      215,  215,  215,  136,  146,  142,  163,  146,  218,  217,
      147,  216,  216,  216,  216,  148,  217,  273,  170,  143,
      217,  170,  200,  150,  217,  150,  150,  217,  235,  149,
      144,  221,  221,  221,  221,  217,  145,  153,  153,  200,
      153,  274,  219,  221,  221,  221,  221,  215,  215,  215,
      215,  282,  281,  152,  152,  152,  152,  154,  163,  221,
      221,  221,  221,  155,  154,  155,  156,  156,  156,  156,

      163,  166,  154,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  293,  165,  293,  157,  157,  157,
      157,  181,  232,  232,  232,  232,  278,  155,  181,  155,
      182,  182,  182,  182,  277,  166,  181,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  293,  165,
      293,  183,  183,  183,  183,  186,  153,  153,  218,  153,
      280,  155,  186,  155,  187,  187,  187,  187,  276,  275,
      186,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  293,  272,  293,  188,  188,  188,  188,  203,
      152,  152,  152,  152,  271,  155,  203,  155,  204,  204,

      204,  204,  270,  269,  203,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  293,  268,  293,  205,
      205,  205,  205,  210,  172,  172,  267,  236,  266,  155,
      210,  155,  211,  211,  211,  211,  265,  172,  210,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      293,  264,  293,  212,  212,  212,  212,  174,  174,  175,
      175,  263,  175,  238,  164,  198,  164,  164,  198,  235,
      174,  165,  166,  165,  165,  180,  279,  180,  180,  164,
      249,  218,  208,  200,  208,  208,  165,  253,  253,  253,
      253,  215,  215,  215,  215,  256,  258,  222,  222,  218,

      222,  257,  257,  257,  257,  221,  221,  221,  221,  232,
      232,  232,  232,  253,  253,  253,  253,  256,  283,  283,
      283,  164,  261,  257,  257,  257,  257,  284,  284,  284,
      285,  285,  285,  286,  286,  286,  287,  287,  287,  200,
      288,  288,  288,  288,  289,  289,  289,  290,  290,  290,
      218,  260,  200,  218,  291,  291,  291,  291,  292,  292,
      292,  218,  255,  254,  252,  251,  200,  218,   51,   51,
       51,   51,   51,   51,   86,   86,   86,   86,   86,   86,
      141,  141,  141,  141,  141,  141,  164,  164,  200,  164,
      164,  164,  165,  165,  165,  165,  165,  165,  169,  166,

      166,  247,  169,  171,  246,  245,  171,  171,  171,  173,
      244,  243,  173,  173,  173,  178,  178,  242,  178,  178,
      178,  179,  179,  179,  179,  179,  179,  191,  191,  241,
      191,  191,  191,  195,  195,  240,  195,  195,  195,  196,
      196,  196,  196,  196,  196,  223,  223,  239,  223,  223,
      229,  229,  237,  229,  229,  229,  230,  230,  230,  230,
      230,  230,  235,  235,  166,  235,  235,  235,  172,  166,
      166,  172,  172,  172,  174,  234,  233,  174,  174,  174,
      248,  248,  231,  248,  248,  248,  262,  262,  164,  262,
      262,  262,  228,  227,  226,  166,  168,  214,  213,  168,

      166,  162,  159,  168,  207,  206,  166,  197,  166,  194,
      193,  192,  168,  190,  189,  168,  185,  184,  158,  151,
      168,  177,  176,  168,  162,  159,  158,  151,  293,   25,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293
    } ;

static yyconst short int yy_chk[966] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,  308,   27,    2,   27,
       27,    2,   41,    9,    6,   41,    2,    6,    8,   48,
        6,    8,   48,  307,    8,    6,   45,  148,   23,    8,
        2,    3,    3,    3,    3,    3,   45,    3,    9,    6,
        3,  148,   23,    8,    9,   12,  291,    3,   12,   54,
       54,   12,   54,   23,   74,  288,   12,   74,    3,   23,
       21,   21,   21,   21,    3,    4,    4,    4,    4,    4,

       12,    4,    4,  281,    4,   21,   43,    4,   43,   43,
       78,    4,   34,   34,   34,   34,   57,   43,  277,   57,
       78,    4,    4,   61,  275,   61,   61,   57,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    7,    7,    7,    7,   97,   97,
      101,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   10,   10,   14,   10,   16,   14,   10,   16,
       14,   83,   16,   10,   83,   14,  101,   16,   94,   52,

       52,   94,   52,   67,   67,   67,   67,   10,   10,   14,
      105,   16,   52,  105,   10,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       13,   13,   13,   13,  132,  132,  271,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   17,   17,   17,   17,  143,  269,  143,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   18,   53,   53,   18,  202,  202,   18,   53,   95,
      267,   76,   18,   76,   76,   53,   95,  108,  122,  108,
      108,  122,   76,  225,   95,  225,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   20,  265,   58,   20,   58,   58,   20,   59,
       59,   59,   59,   20,  110,  110,  110,  110,   96,   58,

      125,  125,  125,  125,   59,   96,  263,   20,   22,   22,
       22,   22,  136,   96,   22,   98,  220,  220,   98,   22,
       96,  139,  139,   22,  139,  115,   98,  115,  115,  126,
      126,  126,  126,   22,   24,   24,  115,   24,  136,  129,
       24,  128,  128,  128,  128,   24,  129,  249,  170,   24,
      131,  170,  249,  150,  129,  150,  150,  131,  262,   24,
       24,  137,  137,  137,  137,  131,   24,   35,   35,  250,
       35,  250,  131,  138,  138,  138,  138,  133,  133,  133,
      133,  261,  260,   35,   35,   35,   35,   36,  133,  140,
      140,  140,  140,   36,   36,   36,   36,   36,   36,   36,

      140,  228,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   39,  228,   39,   39,   39,   39,
       39,   69,  152,  152,  152,  152,  255,   69,   69,   69,
       69,   69,   69,   69,  254,  230,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   72,  230,
       72,   72,   72,   72,   72,   80,  153,  153,  259,  153,
      259,   80,   80,   80,   80,   80,   80,   80,  252,  251,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   81,  247,   81,   81,   81,   81,   81,  102,
      155,  155,  155,  155,  246,  102,  102,  102,  102,  102,

      102,  102,  245,  244,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  103,  243,  103,  103,
      103,  103,  103,  119,  171,  171,  242,  171,  241,  119,
      119,  119,  119,  119,  119,  119,  240,  171,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      120,  234,  120,  120,  120,  120,  120,  173,  173,  175,
      175,  233,  175,  173,  178,  198,  178,  178,  198,  231,
      173,  179,  179,  179,  179,  180,  258,  180,  180,  178,
      201,  258,  208,  201,  208,  208,  179,  209,  209,  209,
      209,  215,  215,  215,  215,  216,  219,  222,  222,  219,

      222,  216,  216,  216,  216,  221,  221,  221,  221,  232,
      232,  232,  232,  253,  253,  253,  253,  257,  264,  264,
      264,  229,  227,  257,  257,  257,  257,  266,  266,  266,
      268,  268,  268,  270,  270,  270,  272,  272,  272,  273,
      274,  274,  274,  273,  276,  276,  276,  278,  278,  278,
      279,  226,  274,  218,  279,  280,  280,  280,  282,  282,
      282,  217,  214,  213,  207,  206,  200,  280,  294,  294,
      294,  294,  294,  294,  295,  295,  295,  295,  295,  295,
      296,  296,  296,  296,  296,  296,  297,  297,  199,  297,
      297,  297,  298,  298,  298,  298,  298,  298,  299,  196,

      194,  193,  299,  300,  192,  190,  300,  300,  300,  301,
      189,  185,  301,  301,  301,  302,  302,  184,  302,  302,
      302,  303,  303,  303,  303,  303,  303,  304,  304,  177,
      304,  304,  304,  305,  305,  176,  305,  305,  305,  306,
      306,  306,  306,  306,  306,  309,  309,  174,  309,  309,
      310,  310,  172,  310,  310,  310,  311,  311,  311,  311,
      311,  311,  312,  312,  167,  312,  312,  312,  313,  165,
      163,  313,  313,  313,  314,  162,  159,  314,  314,  314,
      315,  315,  149,  315,  315,  315,  316,  316,  147,  316,
      316,  316,  146,  145,  144,  135,  124,  123,  121,  118,

      117,  114,  113,  107,  106,  104,  100,   93,   92,   90,
       89,   88,   85,   84,   82,   79,   75,   73,   71,   66,
       60,   56,   55,   46,   42,   40,   38,   33,   25,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
/* 
 *  Copyright (C) 2001, 2000, 1999,  Rildo Pragana. 
 *  Copyright (C) 1993, 1991  Rildo Pragana.
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this software; see the file COPYING.  If not, write to
 *  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 *  Boston, MA 02111-1307 USA
*/ 
/*
**  COBOL scanner 
**  Scanner para o Compilador COBOL
*/
#define YY_NEVER_INTERACTIVE 1
#line 30 "scan.l"
/*
#include "htcoblib.h"
#include "htglobals.h"
#include <ctype.h>
*/
/* #define DEBUG_SCANNER            1 */

#define MAX_COPY_DEPTH          10
#define MAX_CPYNAME_LEN         65
#define MAXLINEBUF              256

void scdebug( char *fmt, ... );
char *savename1(int, int);

#define lexchar input

/* extern int lexgetc(void); */

int source_debug=0;
int envdiv_bypass_save_sw=0;
int stabs_started=0;

/* extern FILE *o_lst; */

int lex_fgets( char *buf, int maxsize );

#define YY_INPUT(buf,result,max_size) \
        { \
                result = lex_fgets( buf, max_size ); \
        }
/*
 Redefines the lexer so that we define yylex to call yylex2 
 and save the token returned by the real lexer (yylex2)
 FIX for FLEX versions greater than 2.5.4 
*/
int prev_token=0;

#ifdef YY_USE_PROTOS
#define YY_DECL int yylex2 YY_PROTO((void))
#else
#define YY_PROTO(proto) (void)
#define YY_DECL int yylex2(void)
#endif

#line 101 "scan.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#include "htglobals.h"
#include "htcoboly.h"
#include "htcobol.tab.h"    /* definitions from YACC */
#include "htcoblib.h"
#include "reswords.h"

#define TOKTEXT_SIZE 1024

char toktext[TOKTEXT_SIZE];
char *tp;
unsigned char hnum[512];
unsigned int varnumber;
int reserved_token;
int previous_state = 0;
short function_seen = 0;
int eos_detect=0;

#define svtoken() strncpy(toktext,yytext,sizeof(toktext))  

#define IDENT_ST 1
#define ENVIR_ST 2
#define DATA_ST 3
#define COMMENT_ST 4
#define FD_ST 5
#define REDEF_ST 6

#define SUBSCRIPTS_ST 7
#define EXCEPTION_ST 8
#define PIC_ST 9
#define PIC_ST2 10
#define COMMENT1_ST 11

#line 850 "scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 130 "scan.l"


        extern int curr_division;
        extern int need_subscripts;
/*        struct copy_symbols *tmp = NULL; */

        switch (curr_division) {
        case CDIV_IDENT:
                scdebug("-> IDENT_ST\n");
                BEGIN IDENT_ST;
                break;
        case CDIV_ENVIR:
                scdebug("-> ENVIR_ST\n");
                BEGIN ENVIR_ST;
                break;
        case CDIV_DATA:
                scdebug("-> DATA_ST\n");
                BEGIN DATA_ST;
                break;
        case CDIV_PROC:
                /* stabs_started=1; */
                scdebug("-> INITIAL\n");
                BEGIN INITIAL;
                break;
        case CDIV_COMMENT:
                scdebug("-> COMMENT_ST\n");
                BEGIN COMMENT_ST;
                break;
        case CDIV_COMMENT1:
                scdebug("-> COMMENT1_ST\n");
                BEGIN COMMENT1_ST;
                break;
        case CDIV_FD:
                scdebug("-> FD_ST\n");
                BEGIN FD_ST;
                break;
        case CDIV_REDEF:
                scdebug("-> REDEF_ST\n");
                BEGIN REDEF_ST;
                break;
        case CDIV_SUBSCRIPTS:
                scdebug("-> SUBSCRIPTS_ST\n");
                BEGIN SUBSCRIPTS_ST;
                break;
        case CDIV_EXCEPTION:
                scdebug("-> EXCEPTION_ST\n");
                BEGIN EXCEPTION_ST;
                break;
        case CDIV_PIC:
                scdebug("-> PIC_ST\n");
                BEGIN PIC_ST;
                break;
        case CINITIAL:
                scdebug("-> INITIAL\n");
                BEGIN INITIAL;
                break;
        }
        curr_division=0; /* avoid new state switch */


#line 1065 "scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 294 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 930 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 190 "scan.l"
{
  char *endp;
  source_lineno = strtol (yytext + 2, &endp, 10);
  if (source_lineno > 0)
    source_lineno--;
  if (source_filename)
    free (source_filename);
  source_filename = strdup (strchr (endp, '"') + 1);
  strrchr (source_filename, '"')[0] = '\0';
  scdebug("NEW FILE/LINE : %s,%d\n", source_filename,source_lineno);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 202 "scan.l"
{ /* throw away this */ }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 204 "scan.l"
{ 
    /* allow floating comment line */  
    scdebug("<comment>: %s:\n", yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 209 "scan.l"
{ 
                if (!source_debug)
                        scdebug("<comment>: %s:\n", yytext);
                else
                        yyless(2);
        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 216 "scan.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 217 "scan.l"
{ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 219 "scan.l"
{
                if (need_subscripts) {
                        scdebug("<LPAR>:\n");
                        need_subscripts=0;
                        return(LPAR);
                }
                else {
                        return('('); 
                }
        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 229 "scan.l"
{ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 231 "scan.l"
{ {
                struct sym *symbol;
                svtoken();
                if (is_integer_token(toktext) && prev_token == PERIOD_TOK) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                } 
                /* if (is_integer_token(toktext) && !eos_detect) {*/
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                eos_detect=0;
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                } 
                else {
                        if ((reserved_token=reserved(toktext))!=0) 
                        {
                                if (reserved_token == FUNCTION) function_seen=TRUE;
                                /* special case of 4 intrinsics which are also reserved */
                                if (function_seen && lookup_intrinsic_sym(toktext) != NULL)
                                {
                                        yylval.sval=install(toktext,SYTB_LAB,0); 
                                        scdebug(" <LABELSTR>: %s\n", toktext);
                                        return(LABELSTR);
                                }
                                scdebug(" <reserved>: %s\n", toktext);
                                return reserved_token;
                        }
                        /* if symbol was defined at the data division */
                        if (symbol=lookup(toktext,2)) {
                                yylval.sval=symbol;
                                if (symbol->type == '8') {
                                        scdebug("<VARCOND>: %s\n",toktext);
                                        update_xreflist(yylval.sval); 
                                        return(VARCOND);
                                }
                                else {
                                        if (is_subscripted(symbol)) {
                                                        scdebug("<SUBSCVAR>: %s\n",toktext);
                                                        return(SUBSCVAR);
                                        }
                                        scdebug("<VARIABLE>: %s\n", toktext);
                                        update_xreflist(yylval.sval); 
                                        return(VARIABLE);
                                }
                        } 
                        /* otherwise, it should be a label */
                        else {
                                yylval.sval=install(toktext,SYTB_LAB,0); 
                                scdebug("<LABELSTR>: %s\n", toktext);
                                return(LABELSTR);
                        }
                }
        } }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 292 "scan.l"
{
                svtoken();
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                }
                else {
                      if ((reserved_token=reserved(toktext))!=0) 
                      {
                         scdebug(" <reserved>: %s\n", toktext);
                         return reserved_token;
                      }
                      scdebug("<STRING>: %s\n", toktext);
                      if (envdiv_bypass_save_sw == 0) {
                         yylval.sval=install(toktext,SYTB_VAR,0);
                         update_xreflist(yylval.sval); 
                      }
                      return(STRING);
                }

}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 320 "scan.l"
{ {
                struct sym *symbol;
                svtoken();
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                }
                else {
                        if ((reserved_token=reserved(toktext))!=0) 
                        {
                                scdebug(" <reserved>: %s\n", toktext);
                                if (reserved_token == NOT)
                                        reserved_token = NOTEXCEP;
                                return reserved_token;
                        }
                        /* if symbol was defined at the data division */
                        if (symbol=lookup(toktext,2)) {
                                yylval.sval=symbol;
                                if (symbol->type == '8') {
                                        scdebug("<VARCOND>: %s\n",toktext);
                                        update_xreflist(yylval.sval); 
                                        return(VARCOND);
                                }
                                else {
                                        scdebug("<VARIABLE>: %s\n", toktext);
                                        update_xreflist(yylval.sval); 
                                        return(VARIABLE);
                                }

                        } 
                        /* otherwise, it should be a label */
                        else {
                                yylval.sval=install(toktext,SYTB_LAB,0);
                                scdebug("<LABELSTR>: %s\n", toktext);
                                return(LABELSTR);
                        }
                }
        } }
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 366 "scan.l"
{
                svtoken();
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                }
                else {
                        if ((reserved_token=reserved(toktext))!=0) 
                        {
                                scdebug(" <reserved>: %s\n", toktext);
                                return reserved_token;
                        }
                        scdebug("<STRING>: %s\n", toktext);
                        /* install w/clone if neccessary */
                        if ((yylval.sval=lookup(toktext,SYTB_VAR))==NULL)
                                yyerror("undefined %s at FD/SD",toktext); 
                        return(STRING);
                }
        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 391 "scan.l"
{ }
	YY_BREAK

case 14:
YY_RULE_SETUP
#line 394 "scan.l"
{
                svtoken();
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                }
                else {
                        if ((reserved_token=reserved(toktext))!=0) 
                        {
                                scdebug(" <reserved>: %s\n", toktext);
                                return reserved_token;
                        }
                        scdebug("<STRING>: %s\n", toktext);
                        /* don't clone redefined var */
                        yylval.sval=install(toktext,SYTB_VAR,0); 
                        update_xreflist(yylval.sval); 
                        return(STRING);
                }
        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 420 "scan.l"
{
                svtoken();
                if (is_integer_token(toktext)) {
                        scdebug("<NLITERAL>: %s\n", toktext);
                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                        return(NLITERAL);
                }
                if (!is_valid_identifier(toktext)) {
                        yylval.sval=install(toktext,SYTB_LAB,0); 
                        scdebug("<LABELSTR>: %s\n", toktext);
                        return(LABELSTR);
                }
                else {
                        if ((reserved_token=reserved(toktext))!=0) 
                        {
                                scdebug(" <reserved>: %s\n", toktext);
                                return reserved_token;
                        }
                        scdebug("<STRING>: %s\n", toktext);
                        /* install w/clone if neccessary */
                        yylval.sval=install(toktext,SYTB_VAR,1);
                        update_xreflist(yylval.sval); 
                        return(STRING);
                }
        }
	YY_BREAK

case 16:
YY_RULE_SETUP
#line 447 "scan.l"
{ }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 448 "scan.l"
{
                svtoken();
                scdebug("<NLITERAL>: %s\n", toktext);
                yylval.lval = (struct lit *)install_lit(&toktext[1],0,0);
                return(NLITERAL);
	} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 455 "scan.l"
{
                svtoken();
                scdebug("<0: any>: %s\n", toktext);
                return(toktext[0]); 
        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 460 "scan.l"
{ }
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 464 "scan.l"
{ }
	YY_BREAK
case 21:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 465 "scan.l"
{ 
                scdebug("<PERIOD_TOK>:\n");
                return(PERIOD_TOK); 
        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 469 "scan.l"
{
                svtoken();
                scdebug(" <IDSTRING_LITERAL>: %s\n", toktext);
                yylval.str=savename1(1, 1);
                return IDSTRING_LITERAL;
        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 475 "scan.l"
{
                svtoken();
                scdebug(" <IDSTRING_LITERAL>: %s\n", toktext);
                yylval.str=savename1(1, 1);
                return IDSTRING_LITERAL;
        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 481 "scan.l"
{
                svtoken();
                scdebug(" <IDSTRING_WORD>: %s\n", toktext);
                yylval.str=toktext;
                return IDSTRING_WORD;
        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 487 "scan.l"
{
                svtoken();
                scdebug("<0: any>: %s\n", toktext);
                return(toktext[0]); 
        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 492 "scan.l"
{ }
	YY_BREAK
/* end of <IDENT_ST> */

case 27:
YY_RULE_SETUP
#line 497 "scan.l"
{ }
	YY_BREAK
case 28:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 498 "scan.l"
{ 
                scdebug("<PERIOD_TOK>:\n");
                eos_detect++;
                return(PERIOD_TOK); 
        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 504 "scan.l"
{
                tp=toktext;
                while(1) {
                        while((*tp=lexchar())!='"') {
                                if (tp >= toktext+TOKTEXT_SIZE) {
                                        yyerror("scanner error: token too large");
                                        while(lexchar()!='"') ;
                                        *tp=0;
                                        scdebug("<CLITERAL>: %s\n", toktext);
                                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                                        return(CLITERAL);
                                }
                                tp++;
                        }
                        /* replace two consecutives '"' by one and continue */
                        if ((*tp=lexchar())=='"') {
                                tp++;
                                continue;
                        }
                        else {
                                unput(*tp);
                                break;
                        }
                }
                *tp=0;
                scdebug("<CLITERAL>: %s\n", toktext);
                yylval.lval = (struct lit *)install_lit(toktext,0,0);
                return(CLITERAL);
        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 534 "scan.l"
{ 
       {
                unsigned char *s=hnum;
                int len;
                tp=toktext;
                while((*tp=toupper(lexchar()))!='\'') {
                                if (tp >= toktext+TOKTEXT_SIZE) {
                                        yyerror("scanner error: token too large");
                                        while(lexchar()!='\'') ;
                                        *tp=0;
                                        scdebug("<CLITERAL>: %s\n", toktext);
                                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                                        return(CLITERAL);
                                }
                        *s = (*tp > '9') ?
                                (*tp - 'A' + 0x0a) : (*tp - '0');
                        if ((*tp=toupper(lexchar()))=='\'') {
                                break;
                        }
                        *s++ = *s * 0x10 + ((*tp > '9') ? 
                                (*tp - 'A' + 0x0a) : (*tp - '0'));
                }
                len = (int) (s - hnum);
                yylval.lval = (struct lit *)install_lit(hnum,len,0);
                scdebug("<CLITERAL>: %s\n", hnum);
                return(CLITERAL);
       } 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 563 "scan.l"
{ 
       {
                unsigned char *s=hnum;
                int len;
                tp=toktext;
                while((*tp=toupper(lexchar()))!='\"') {
                                if (tp >= toktext+TOKTEXT_SIZE) {
                                        yyerror("scanner error: token too large");
                                        while(lexchar()!='\"') ;
                                        *tp=0;
                                        scdebug("<CLITERAL>: %s\n", toktext);
                                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                                        return(CLITERAL);
                                }
                        *s = (*tp > '9') ?
                                (*tp - 'A' + 0x0a) : (*tp - '0');
                        if ((*tp=toupper(lexchar()))=='\"') {
                                break;
                        }
                        *s++ = *s * 0x10 + ((*tp > '9') ?
                                (*tp - 'A' + 0x0a) : (*tp - '0'));
                }
                len = (int) (s - hnum);
                yylval.lval = (struct lit *)install_lit(hnum,len,0);
                scdebug("<CLITERAL>: %s\n", hnum);
                return(CLITERAL);
       } 
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 592 "scan.l"
{
                tp=toktext;
                while(1) {
                        while((*tp=lexchar())!='\'') { 
                                if (tp >= toktext+TOKTEXT_SIZE) {
                                        yyerror("scanner error: token too large");
                                        while(lexchar()!='\'') ;
                                        *tp=0;
                                        scdebug("<CLITERAL>: %s\n", toktext);
                                        yylval.lval = (struct lit *)install_lit(toktext,0,0);
                                        return(CLITERAL);
                                }
                                tp++;
                        }
                        /* replace two consecutives '\'' by one and continue */
                        if ((*tp=lexchar())=='\'') {
                                tp++;
                                continue;
                        }
                        else {
                                unput(*tp);
                                break;
                        }
                }
                *tp=0;
                yylval.lval = (struct lit *)install_lit(toktext,0,0);
                scdebug("<CLITERAL>: %s\n", toktext);
                return(CLITERAL);
        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 622 "scan.l"
{
                svtoken();
                scdebug("<NLITERAL>: %s\n", toktext);
                yylval.lval = (struct lit *)install_lit(toktext,0,0);
                return(NLITERAL);
        }
	YY_BREAK
 /*
{digit}({exletter}|{digit})* { 
        svtoken();
        scdebug("<LABELSTR>: %s\n", toktext);
        yylval.sval=install(toktext,SYTB_LAB,0);
        return(LABELSTR); 
        }
*/ 

case 34:
YY_RULE_SETUP
#line 638 "scan.l"
{ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 641 "scan.l"
{
                svtoken();
                if ((reserved_token=reserved(toktext))!=0) {
                        scdebug(" <reserved>: %s\n", toktext);
                        return reserved_token;
                }
                yyerror("relational operator unknown");
        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 650 "scan.l"
{
                svtoken();
                if (function_seen) {
                        function_seen=FALSE;
                        }
                scdebug("<0: lpar>: %s\n", toktext);
                return(toktext[0]); 
        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 658 "scan.l"
{
                svtoken();
                scdebug("<0: POW_OP>: %s\n", toktext);
                return(POW_OP); 
        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 663 "scan.l"
{ }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 664 "scan.l"
{ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 665 "scan.l"
{
                svtoken();
                scdebug("<0: any>: %s\n", toktext);
                return(toktext[0]); 
        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 671 "scan.l"
{ }      
	YY_BREAK
/* end of <INITIAL,DATA_ST,ENVIR_ST> */

case 42:
YY_RULE_SETUP
#line 676 "scan.l"
{ 
         svtoken();
         scdebug(" <COMMENT_ST>: %s\n", toktext);
       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 680 "scan.l"
{ BEGIN INITIAL; }
	YY_BREAK
/* end of COMMENT_ST */

case 44:
YY_RULE_SETUP
#line 684 "scan.l"
{ 
         svtoken();
         scdebug(" <COMMENT1_ST>:>>%s<<:\n", toktext);
        }
	YY_BREAK
case 45:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 688 "scan.l"
{ 
         svtoken();
         scdebug(" <COMMENT1_ST>:>>%s<<:\n", toktext);
         BEGIN INITIAL; 
       }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 693 "scan.l"
{ 
         svtoken();
         scdebug(" <COMMENT1_ST>:>>%s<<:\n", toktext);
       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 697 "scan.l"
{ 
         svtoken();
         scdebug(" <COMMENT1_ST>:<NL>:\n");
       }
	YY_BREAK
/* end of COMMENT1_ST */
case 48:
YY_RULE_SETUP
#line 703 "scan.l"
{ 
                BEGIN PIC_ST2;
                scdebug("<PICS -> PIC_ST2>:\n");
        }
	YY_BREAK

case 49:
YY_RULE_SETUP
#line 709 "scan.l"
{ 
                BEGIN DATA_ST;
                scdebug("<PICS -> DATA_ST>:\n");
        }
	YY_BREAK
case 50:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 713 "scan.l"
{ 
                BEGIN DATA_ST;
                scdebug("<PICS -> DATA_ST>: PERIOD_TOK\n");
                return PERIOD_TOK;
        }
	YY_BREAK


case 51:
YY_RULE_SETUP
#line 721 "scan.l"
{ 
                { 
                char *s;
                yylval.ival = 0;
                s = yytext+1; /* bypass lpar */
                while (*s!=')')
                        yylval.ival = 10 * yylval.ival + *s++ - '0';
                scdebug("<PICS: MULTIPLIER>: %d\n", yylval.ival);
                return(MULTIPLIER); 
                } 
        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 732 "scan.l"
{
                svtoken();
                if ((reserved_token=reserved(toktext))!=0) 
                {
                        scdebug(" <reserved>: %s\n", toktext);
                        BEGIN PIC_ST;
                        scdebug("<PIC_ST2-> PIC_ST>:\n");
                        return reserved_token;
                }
                REJECT;
        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 743 "scan.l"
{ }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 744 "scan.l"
{ 
                scdebug("<PICS: any char>: %c\n", yytext[0]);
                yylval.ival=(int)yytext[0];
                return(CHAR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 748 "scan.l"
{ }
	YY_BREAK
/* end of PICS */
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IDENT_ST):
case YY_STATE_EOF(ENVIR_ST):
case YY_STATE_EOF(DATA_ST):
case YY_STATE_EOF(COMMENT_ST):
case YY_STATE_EOF(FD_ST):
case YY_STATE_EOF(REDEF_ST):
case YY_STATE_EOF(SUBSCRIPTS_ST):
case YY_STATE_EOF(EXCEPTION_ST):
case YY_STATE_EOF(PIC_ST):
case YY_STATE_EOF(PIC_ST2):
case YY_STATE_EOF(COMMENT1_ST):
#line 751 "scan.l"
{
        yyterminate();
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 755 "scan.l"
{svtoken();
         scdebug("invalid character:>>%x<<:\n", (unsigned char)toktext[0]);
         yyerror("invalid character:>>%x<<:\n", (unsigned char)toktext[0]);
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 759 "scan.l"
ECHO;
	YY_BREAK
#line 1943 "scan.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 294 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 294 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 293);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 759 "scan.l"


int yylex YY_PROTO((void))
{
	prev_token = yylex2();
	/*printf("tok:%x\n", prev_token);*/
	return prev_token;
}

int is_integer_token( char *tok ) {
        while (isdigit(*tok)) tok++;
        if (*tok=='\0') return 1;
        return 0;
}

int is_valid_identifier( char *tok ) {
        while (*tok && !isalpha(*tok)) tok++;
        if (*tok=='\0') {
                return 0;
        }
        return 1;
}

int lex_fgets( char *buf, int maxsize ) {
        int result;
        char *s;
        s = fgets( buf,maxsize,yyin );
        result = (s==NULL) ? YY_NULL: strlen(s);
/*	result = fread( buf, 1, maxsize, yyin); */
        if (result) { 
                result = strlen(buf);
                ++source_lineno; 
        } 
        return result;
}

char *savename1(int x1, int x2) {
  char *s2, *s1;
  int len;
  
  s1 = toktext;
  len = strlen(s1);
  if (len - x1 - x2 > 0) {
    s2 = s1 + len - x2;
    *s2 = '\0';
    s1 = toktext;
    s2 = s1 + x1;
    while (*s1 != '\0') {
      *s1 = *s2;
      s1++;
      s2++;
    }
  }
  return(toktext);
}

/*
char *savename( char *name );
int hash( char *name );
*/

#if defined(SunOS)
va_list __builtin_va_alist;
#endif

void scdebug( char *fmt, ... ) {
        va_list args;
        va_start(args,fmt);
#ifdef DEBUG_SCANNER
        fprintf(stderr,"SCAN(%4d):",source_lineno);
        vfprintf(stderr,fmt,args);
#endif
        va_end(args);
}

int yywrap() { return 1; }

/* end of scan.l */
